// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ-fDpMU0R2F_QGsTYilNA36cv1d5k9CA',
    appId: '1:336834185335:web:075b2dca85cb331a7d1e72',
    messagingSenderId: '336834185335',
    projectId: 'osama-chat-def1b',
    authDomain: 'osama-chat-def1b.firebaseapp.com',
    storageBucket: 'osama-chat-def1b.appspot.com',
    measurementId: 'G-3SXBSF49DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6dppl7U18XzrlMrXmXqtzvl6RZZnjKkE',
    appId: '1:336834185335:android:1117e43a8a991e0c7d1e72',
    messagingSenderId: '336834185335',
    projectId: 'osama-chat-def1b',
    storageBucket: 'osama-chat-def1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKbjpXoKw1TUTNhHcrAg09iQapkhYy0JU',
    appId: '1:336834185335:ios:ee5e20cf5e9b2e927d1e72',
    messagingSenderId: '336834185335',
    projectId: 'osama-chat-def1b',
    storageBucket: 'osama-chat-def1b.appspot.com',
    androidClientId: '336834185335-tt3nb5s3gp9nk9la6jv9df6lbq6uh70n.apps.googleusercontent.com',
    iosClientId: '336834185335-s6qpn7bgtdne4bhls4keh303kat2bsvd.apps.googleusercontent.com',
    iosBundleId: 'c',
  );
}
